cfg: models/yolov5s.yaml
data: ./data/gun_dataset.yaml
hyp: ''
epochs: 300
batch_size: 24
img_size:
- 416
- 416
rect: false
resume: store_false
nosave: true
notest: true
noautoanchor: true
evolve: false
bucket: ''
cache_images: false
weights: ./weights/yolov5s.pt
name: yolov5s_train
device: '0'
multi_scale: false
single_cls: false
