cfg: models/yolov5m.yaml
data: ./data/gun_dataset.yaml
hyp: ''
epochs: 350
batch_size: 32
img_size:
- 416
- 416
rect: true
resume: store_false
nosave: true
notest: true
noautoanchor: true
evolve: false
bucket: ''
cache_images: false
weights: ./weights/yolov5m.pt
name: yolov5m_train
device: '0'
multi_scale: false
single_cls: false
dataList: ./data/train_img_list.txt
randomImg: /home/ali/ProjLAB/DATA/NEWGUN/images/
